### ISSUE TITLE
CHARACTER SET can also be written as CHAR SET in MySQL

### ISSUE THREAD

**Issue by maryo** [SQLFTW/sqlftw#12]
Hi ;-)

`CHARACTER SET` can not only be written as `CHARSET` but also `CHAR SET`, at least in MySQL.
Certain holomek used it in our migrations and the statement resolved into an instance of `InvalidCommand`.

```sql
CREATE TABLE foo (id int) CHAR SET=utf8;
ALTER TABLE foo ADD COLUMN bar VARCHAR(255) CHAR SET latin1;
```

**Comment by paranoiq** [comment]
wow. and there is not a single test for this in the whole mysql-server test suite 🤦‍♂️

will be fixed soon

**Comment by paranoiq** [comment]
will be fixed in next release: https://github.com/SQLFTW/sqlftw/commit/8cbe6793e2c0810db0cb35274207010578a4283c
