### ISSUE TITLE
Assigment operation

### ISSUE THREAD

**Issue by shatrovalexey** [SQLFTW/sqlftw#19]
Input:
```
INSERT IGNORE INTO
	`x`
SET
	`y` := @`yyy` ;
```
output:
```
Expected token OPERATOR with value =, but token SYMBOL|OPERATOR with value ":=" (2) found instead at position 6 in
```

There may be assigment operators or comparsion operators. Do not confuse. But MySQL in some cases allows to use comparsion operator as assignment (MySQL loose).
```
UPDATE `x` SET `x`.`y` := :y WHERE ( `x`.`z` = :z ) ;
```

**Comment by paranoiq** [comment]
yep. this is a bug. will be fixed in next release: https://github.com/SQLFTW/sqlftw/commit/873c007e6ec686da94680540e8ac105e40837ef3
