### ISSUE TITLE
sqlftw release contains a bunch of unncessary files

### ISSUE THREAD

**Issue by staabm** [SQLFTW/sqlftw#23]
similar to https://github.com/paranoiq/dogma-dev/issues/1 I think a release should not contain these folders:
- build
- doc
- tests

<img width="374" alt="grafik" src="https://user-images.githubusercontent.com/120441/225752995-fe80139d-314a-4a5c-83c8-64b2f256dda3.png">

**Comment by paranoiq** [comment]
👍 removed

**Comment by staabm** [comment]
Thank you 🙏
