### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by staabm** [SQLFTW/sqlftw#25]
could you please add the LICSENSE this project is using?

**Comment by dergel** [comment]
ping. Are there any news? MIT License would be great.

**Comment by xsist10** [comment]
+1 on this. I'm exploring using this library for another open source project, but can't do much beyond a basic viability check until I have some idea of the licensing.

I see your code mentions looking at the `license.md` (see [source](https://github.com/SQLFTW/sqlftw/blob/master/sources/SqlFtwException.php#L7)) but it doesn't appear to have been included in the repo.

**Comment by staabm** [comment]
@paranoiq could you please add a license?

**Comment by paranoiq** [comment]
hi, all. 
i am well aware of this issue. **no need to remind me** 

not a long time ago i was talking about this with [@ondrejmirtes](https://github.com/ondrejmirtes). with PHPStan, Ondra was lucky to find a huge niche and both dedicated and skilful enough in the soft-skill areas to be able to do it his full time job. but this differs project to project and person to person.

SQLFTW started as a hobby project and i am enjoying to develop it just for fun, but at the same time, i am not ready to "give it away" by using too permissive licencense like, for example, MIT. 

i have seen a few people regretting either this decision, or the situation they got into, with supporting a hugely used project on their free time, struggling to cope with it and not able to work on it as their daily job. i think that by releasing this project with a licence that does not guarantee a fair usage for all sides (this project maintainer(s), the lib authors - you, the end users) i could end up severely limiting the scope of this project in the long run.

license will be added, when i am ready to decide
